### ISSUE TITLE
Please supply API version (YYYY-MM-DD) as CB-VERSION header

### ISSUE THREAD

**Issue by bennyn** [coinbase/coinbase-node#100]
I executed `client.getSellPrice({'currencyPair': 'ETH-USD'}` and received the following response from Coinbase:

```json
{
  "data": {
    "base": "ETH",
    "currency": "USD",
    "amount": "752.43"
  },
  "warnings": [
    {
      "id": "missing_version",
      "message": "Please supply API version (YYYY-MM-DD) as CB-VERSION header",
      "url": "https://developers.coinbase.com/api#versioning"
    }
  ]
}
```

Checking [lib/ClientBase.js](https://github.com/coinbase/coinbase-node/blob/2.0.6/lib/ClientBase.js) I noticed the following in the source code which sets the headers:

```
'CB-VERSION': this.version || '2016-02-18'
```

I think it should be just ` 'CB-VERSION': '2016-02-18'` to get rid of the response warning.

**Comment by irkanu** [comment]
@bennyn You can pass version when you are instantiating Client.

![screenshot_2105](https://user-images.githubusercontent.com/6570433/38158255-c559fac8-345e-11e8-8809-971a7d52ba11.png)

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
