### ISSUE TITLE
[SECURITY] node-uuid: crypto not usable

### ISSUE THREAD

**Issue by lunafi-evan** [coinbase/coinbase-node#102]
I get this error when running in unit tests:

```
 console.warn node_modules/coinbase/node_modules/node-uuid/uuid.js:48
 [SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()
```

It looks like the [node-uuid](https://www.npmjs.com/package/node-uuid) package has been deprecated in favor of  the [uuid](https://www.npmjs.com/package/uuid) package.

**Comment by jako-hub-old** [comment]
Same error here.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
