### ISSUE TITLE
tests use address.label but should use address.name

### ISSUE THREAD

**Issue by lunafi-evan** [coinbase/coinbase-node#103]
See this test:

[https://github.com/coinbase/coinbase-node/blob/d83f34aae232dd561e8192ce4deb5e127fcf0366/test/testAccount.js#L101](https://github.com/coinbase/coinbase-node/blob/d83f34aae232dd561e8192ce4deb5e127fcf0366/test/testAccount.js#L101)
```js
btcAccount.createAddress(args, function(err, result) {
    assert.equal(err, null, err);
    assert(result);
    assert.equal(result.label, na.CREATE_ADDRESS_RESP.data.label,
      "can not create address: " + JSON.stringify(result));
  });
```

The coinbase API currently doesn't include a "label" property but a "name" property. Passing `{ name: 'my name' }` into `btcAccount.createAddress` works as expected, the test/example needs to be updated.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
