### ISSUE TITLE
"sendMoney" to_financial_institution and financial_institution_website support

### ISSUE THREAD

**Issue by lunafi-evan** [coinbase/coinbase-node#104]
According to the "send money" [API docs](https://developers.coinbase.com/api/v2?shell#send-money), the `to_financial_institution` and `financial_institution_website` parameters are required for sending money worth more than $3,000 but there's no example of this in the unit tests, and the code's docblock comments don't mention it anywhere.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
