### ISSUE TITLE
Buy unit test is incorrect, no working example

### ISSUE THREAD

**Issue by lunafi-evan** [coinbase/coinbase-node#108]
The unit test for purchasing cryptocurrency [on this line](https://github.com/coinbase/coinbase-node/blob/d83f34aae232dd561e8192ce4deb5e127fcf0366/test/testAccount.js#L181) fails against the real API. The correct usage is as follows:

```js
 btcAccount.buy({ amount: 0.5, currency: 'BTC' })
```

This seems redundant since `btcAccount` should be aware that it is for BTC, so `currency` param shouldn't be necessary.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
