### ISSUE TITLE
Account "sell" method doesn't add description to transaction

### ISSUE THREAD

**Issue by lunafi-evan** [coinbase/coinbase-node#109]
Adding the `description` option to `btcAccount.sell()` doesnt add the description to the transaction, even though it should be able to since the Transaction resource supports a description.

This doesn't attach a description to the transaction
```js
btcAccount.sell({
    amount: 100,
    currency: 'BTC',
    description: 'my description'
 })
```

But this does
```js
btcAccount.buy({
    amount: 100,
    currency: 'BTC',
    description: 'my description'
 })
```

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
