### ISSUE TITLE
Published version fails to install dependency

### ISSUE THREAD

**Issue by scarrick68** [coinbase/coinbase-node#114]
The published version tries to install a package called pinkie-promies. That package doesn't exist on npm anymore. It tries to redirected but fails. I think pinkie might be what it's looking for. It works if I clone master and use the local path in my package.json. I think the published version is just out of date.

**Comment by lpfeup** [comment]
@scarrick68 this was an issue with npm.
For more info:
* [NPM](https://status.npmjs.org/incidents/41zfb8qpvrdj)
* [GitHub Issue](https://github.com/npm/registry/issues/255)

**Comment by scarrick68** [comment]
Yea, thanks @Ipfeup. I was just coming to update this. Anyone DL'ing these packages please note security concerns: https://news.ycombinator.com/item?id=16087079

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
