### ISSUE TITLE
How to Increase Limit Show List Addresses

### ISSUE THREAD

**Issue by igun997** [coinbase/coinbase-node#117]
I have 100 List address, and i want to show all ? how to show it  ? https://developers.coinbase.com/api/v2?shell#address-resource, and in Official Documentation , List Address have a limit 25 / page how to increase it or how to switch from 0-24 to 24 - 29

**Comment by 001123** [comment]
Same issue :'( plz help

**Comment by igun997** [comment]
@001123 i has solved that problem , you just save to your database , or grab with hash .
your hash saved on database ,and that hash used on API Coinbase to show transaction. and your problem solved,

**Comment by 001123** [comment]
Still no answer :'(

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
