### ISSUE TITLE
ReferenceError: etypes is not defined, when calling Client.refresh

### ISSUE THREAD

**Issue by joelachance** [coinbase/coinbase-node#118]
I'm trying to refresh an accessToken/refreshToken pair, and calling the refresh method on client isn't working properly. In the Client logic on LOC 39 `err.type = etypes.TokenRefreshError;`, err is an html 404 page.

Any ideas on how to refresh tokens with this library? 
If this is a known issue or is broken I'm happy to submit a PR.

**Comment by lustigo** [comment]
Same happened to me

**Comment by lustigo** [comment]
Duplicate to #72

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
