### ISSUE TITLE
Creating New Address

### ISSUE THREAD

**Issue by sedoyjan** [coinbase/coinbase-node#119]
Hello

I`ve got a problem

I need to create new address for the primary account

```
client.getAccount('82de7fcd-db72-5085-8ceb-bee19303080b', function(err, account) {
  account.createAddress(null, function(err, address) {
    console.log(address);
  });
});
```

but i have the same address

It was working well few days ago

Help me please

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
