### ISSUE TITLE
CoinBase client API doesn't work.

### ISSUE THREAD

**Issue by Appleboy3294** [coinbase/coinbase-node#120]
I was trying to use Resquest Money and Sending Money request in this API.
It works sometimes, but doesn't work permanently.
Whenever I change the sample parameters manually, it works a few times.
But doesn't work soon.
var args = {
            'to': 'email@example.com',
            'amount': '1',
            'currency': 'BTC'
        };
        
        account.requestMoney(args, function(err, txn) {
            console.log('my txn id is: ' + txn.id);
            res.send(txn.id);
        });

**Comment by lustigo** [comment]
Same happend to me, when i comment that line out, I´ll get a 404-Not found Error from the Coinbaseserver

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
