### ISSUE TITLE
Doc in coinbase is wrong. miss an {} in getPaymentMethods

### ISSUE THREAD

**Issue by Denly** [coinbase/coinbase-node#121]
miss an {}

```
// doc
client.getPaymentMethods(function(err, pms) {
  console.log(pms);
});

// should be
client.getPaymentMethods({}, function(err, pms) {
  console.log(pms);
});
```

**Comment by joepagan** [comment]
Looks like this issue is the same as this:
https://github.com/coinbase/coinbase-node/issues/86

I presume there are probably others too.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
