### ISSUE TITLE
Is possible to get address from transaction list

### ISSUE THREAD

**Issue by CaiooAndrade** [coinbase/coinbase-node#127]
How I can get the address from a transaction though NodeJS with CoinbaseApi. I already can do that by Looping though account, then looping though addresses and then, looping though transactions. (Example Code)

```
client.getAccount('82de7fcd-db72-5085-8ceb-bee19303080b', function(err, account) {
  account.getAddresses(null,(err, addresses)=> {
    addresses.forEach(addr=>{
      addr.getTransactions({}, function(err, txs) {
          console.log(addr,txs);
      });
    })
  });
});
```

But is it possible to loop only by Account and Transactions?

I already has this code

```
client.getAccount('82de7fcd-db72-5085-8ceb-bee19303080b', function(err, account) {
    account.getTransactions(null, function(err, txns) {
      console.log('transactions',txns)
    });
});
```
But I can't find the address who received the transaction.

If that isn't possible, each time that I receive a transaction, I need to loop though all addresses, to find that transaction?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
