### ISSUE TITLE
Coinbase-node Lodash dependency Vulnerability.

### ISSUE THREAD

**Issue by surhargev00** [coinbase/coinbase-node#128]
The current coinbase-node.js library uses the version 3.1.0 of the Lodash module. 

This version has a reported vulnerability, which can be used to perform a prototype pollution attack. In most cases it can be used to break the express module, crashing the server and return a 500 error to ulterior requests.
The npm report of the vulnerability can be found [here](https://www.npmjs.com/advisories/577) and the complete report of the vulnerability can be found [here](https://hackerone.com/reports/310443). The below code snippet was provided in the original report and demonstrates how a potential attack could be performed:

```
var _= require('lodash');
var malicious_payload = '{"__proto__":{"oops":"It works !"}}';

var a = {};
console.log("Before : " + a.oops);
_.merge({}, JSON.parse(malicious_payload));
console.log("After : " + a.oops);
```

To solve this issue please update to the current version, or any version above 4.17.5

**Comment by rogierschouten** [comment]
https://npmjs.com/advisories/577

**Comment by rogierschouten** [comment]
https://npmjs.com/advisories/782

**Comment by rogierschouten** [comment]
https://npmjs.com/advisories/1065

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
