### ISSUE TITLE
OAuth creds to get application token

### ISSUE THREAD

**Issue by tracend** [coinbase/coinbase-node#13]
This is more of a question than a report. 

I know you can use API creds to get an application level token:
```
var client = new Client({'apiKey': mykey, 'apiSecret': mysecret});
```
But when using OAuth, the same key names are used for ```client_id``` & ```client_secret```
```
var client = new Client({
                          'apiKey'       : client_id,
                          'apiSecret'    : client_secret,
                          'accessToken'  : accessToken,
                          'refreshToken' : refreshToken
});
```
Does that mean you can use ```client_id``` & ```client_secret``` to get an application level token? 
```
var client = new Client({'apiKey': client_id, 'apiSecret': client_secret});
```
Thanks

**Comment by jorilallo** [comment]
This seems actually a bug in the code and docs, you don't need api keys when handling oauth tokens. Something I need to fix, thanks for pointing this out

**Comment by jorilallo** [comment]
This has been fixed, updating to npm now
