### ISSUE TITLE
account.getAddresses() throw exception

### ISSUE THREAD

**Issue by basit1327** [coinbase/coinbase-node#130]
iam trying to get my account address i follow the documentation as wrote there 
`client.getAccount('82de7fcd-db72-5085-8ceb-bee19303080b', function(err, account) {
  account.getAddresses(function(err, addresses) {
    console.log(addresses);
  });
});`

it get the account but it throw exception at getAddresses =>
`if (!callback) {throw "no callback - check method signature";}`

any how getAddress( ) is working fine just getAddresses() is not fine

**Comment by basit1327** [comment]
same problem with createAddress() please resolve this issue

**Comment by basit1327** [comment]
the issue is typo 
as mention in documention [https://developers.coinbase.com/api/v2#list-addresses](url) 
the getAddresses function takes only callback as argument 
this lead to a exception
but when i try by passing first argument as null and second argument as callback its work properly

**Comment by knoxcard** [comment]
Nice, thanks for sharing that.  I've made that same mistake numerous times, parameter/callback order confusion.  Close ticket?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
