### ISSUE TITLE
Unable to get Transactions of my eth and ltc addresses

### ISSUE THREAD

**Issue by HRNaudZ** [coinbase/coinbase-node#132]
I'm trying to get transactions of one of my eth addresses and I'm getting **"can not read property getTtransactions of null"**. When I did the same thing with a btc address it worked !

My code is this : 

            client.getAccount(myEthAccountId, function(err, account) {
                account.getAddress(myEthAdress, function(err, address) {
                    address.getTransactions({}, function(err, txs) {
                        txs.forEach(elt => {
                            console.log(elt.amount.amount)
                        });
                    });
                });
            });

Thanks !

**Comment by knoxcard** [comment]
does err output anything?

```
if(err)
 console.log('err: ' + err)
```

**Comment by HRNaudZ** [comment]
Sorry but i don't use this api anymore !

Thanks for answering !!!
