### ISSUE TITLE
npm audit high severity issue

### ISSUE THREAD

**Issue by songsc** [coinbase/coinbase-node#134]
Running npm audit for coinbase@2.0.8, we get the following message:
High: Insufficient Entropy
Package: cryptiles
Dependency of: coinbase
Path: coinbase > request > hawk > cryptiles
More info: https://nodesecurity.io/advisories/720
Please update request to newer version.

**Comment by knoxcard** [comment]
I submitted a pull request to bump to latest version: 2.88

https://github.com/coinbase/coinbase-node/pull/135

**Comment by halfcreative** [comment]
Almost been a whole year since this was pointed out, any updates on when we might see this pull request approved and implemented?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
