### ISSUE TITLE
Wrong documentation for "List buys"

### ISSUE THREAD

**Issue by bennycode** [coinbase/coinbase-node#136]
I checked out the documentation on [List Buys](https://developers.coinbase.com/api/v2?javascript#list-buys) which shows this example:

```js
var Client = require('coinbase').Client;

var client = new Client({'apiKey': 'API KEY',
                         'apiSecret': 'API SECRET'});

client.getAccount('2bbf394c-193b-5b2a-9155-3b4732659ede', function(err, account) {
  account.getBuys(function(err, txs) {
    console.log(txs);
  });
});
```

When executing `account.getBuys`, I am getting the following error (using `coinbase` v2.0.8):

> node_modules\coinbase\lib\errorHandler.js:60
>  if (!callback) {throw "no callback - check method signature";}

What I ended up doing was executing `getBuys` with `null` being the first parameter:

```js
client.getAccount('2bbf394c-193b-5b2a-9155-3b4732659ede', function(err, account) {
  account.getBuys(null, function(err, txs) {
    console.log(txs);
  });
});
```

That's also what you do [in your tests](https://github.com/coinbase/coinbase-node/blob/2.0.8/test/testAccount.js#L171). So the Coinbase Node.js API documentation needs to be updated.

I guess the same applies to `account.getSells`?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
