### ISSUE TITLE
sendMoney broken after 2019-03-22 maintenance(idem ValidationError)

### ISSUE THREAD

**Issue by johnsmith888** [coinbase/coinbase-node#139]
Your node API example not works anymore either:

> var Client = require('coinbase').Client;
> var client = new Client({'apiKey': 'API KEY',
>                          'apiSecret': 'API SECRET'});
> 
> client.getAccount('2bbf394c-193b-5b2a-9155-3b4732659ede', function(err, account) {
>   account.sendMoney({'to': '1AUJ8z5RuHRTqD1eikyfUUetzGmdWLGkpT',
>                      'amount': '0.1',
>                      'currency': 'BTC',
>                      'idem': '9316dd16-0c05'}, function(err, tx) {
>     console.log(tx);
>   });
> });

The only idem value works for me is `Date.now()` now

**Comment by joepagan** [comment]
Thanks for highlighting what actually works, shame Coinbase's docs only tell half the story most of the time.

It really is disappointing considering they are probably the most well-used crypto marketplace and likely have enough resources to throw at making suitable docs & a support team which are only going to benefit them financially in the long run.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
