### ISSUE TITLE
Get subscription from custom value

### ISSUE THREAD

**Issue by tracend** [coinbase/coinbase-node#14]
Regarding this endpoint:
https://developers.coinbase.com/api#show-a-subscription

Getting subscription details works with the id created by the api but not with the custom value passed by the merchant.

To be inline with all the other endpoints, like ```orders```, ```buttons``` the ```subscribers``` endpoint should support lookup with the custom value.

**Comment by jorilallo** [comment]
Subscriber IDs are actually separate from order IDs so unfortunately this isn't possible.

**Comment by tracend** [comment]
Yes, Subscriber IDs are separate from order IDs but the custom value the merchant broadcasts is passed through to the subscription. 

So it is possible ;)

**Comment by jorilallo** [comment]
We'll most likely do subscriptions pretty differently with the upcoming API v2 and `custom` field will be quite different there ;)

**Comment by tracend** [comment]
hmm, that's a bit concerning.

**Comment by jorilallo** [comment]
It will actually be quite a lot more flexible. V1 isn't going anywhere but right now we're quite focused on getting v2 out of the door

**Comment by tracend** [comment]
Cool. So is there any way currently, legacy as it may be, to connect an order to a subscription, without extensive lookup?
