### ISSUE TITLE
API crashes on 502 Bad Gateway errors

### ISSUE THREAD

**Issue by bennycode** [coinbase/coinbase-node#140]
When the coinbase servers have trouble and the `request` library (which is a dependency of this API) casts a `BadGatewayError` (HTTP code 502), then the whole API crashes. 

The crash happens within [createError](https://github.com/coinbase/coinbase-node/blob/2.0.8/lib/errorHandler.js#L50) and is bubbled up to [handleHttpError](https://github.com/coinbase/coinbase-node/blob/2.0.8/lib/ClientBase.js#L160).

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
