### ISSUE TITLE
When is something going to be done here?

### ISSUE THREAD

**Issue by knoxcard** [coinbase/coinbase-node#141]
@kbcbhq 
**warning coinbase** > request > hawk@6.0.2: This version has been deprecated. Please upgrade to the latest version to get the best features, bug fixes, and security patches.

**warning coinbase** > request > hawk > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

**warning coinbase** > request > hawk > cryptiles@3.1.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

**warning coinbase** > request > hawk > sntp@2.1.0: This version has been deprecated. Please upgrade to the latest version to get the best features, bug fixes, and security patches.

**warning coinbase** > request > hawk > sntp > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

**warning coinbase** > request > hawk > boom@4.3.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

**warning coinbase** > request > hawk > cryptiles > boom@5.2.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

**warning coinbase** > request > hawk > boom > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

**warning coinbase** > request > hawk > cryptiles > boom > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

**Comment by knoxcard** [comment]
@kbcbhq

**Comment by Alevale** [comment]
The project hasn't been touched in more than a year, I am starting to ask myself if the package is even under development, or maintenance of any kind.

**Comment by knoxcard** [comment]
Seems like they are too busy making a profit.  Not good Coinbase.  Focus on your developer libraries and you can be earning 100x more.

**Comment by Johann-S** [comment]
Maybe someone maintained an up to date version ?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
