### ISSUE TITLE
Cant get Coinbase Api to work with Gatsby or Next.js. 

### ISSUE THREAD

**Issue by SwarmMonkey** [coinbase/coinbase-node#142]
I am trying to build an app that allows users to sign in. This is the error that I keep getting on both gatsby and next.js.

`./node_modules/coinbase/node_modules/request/lib/har.js
Module not found: Can't resolve 'fs' in '/Users/patrickmanfra/Desktop/outlet-loans/node_modules/coinbase/node_modules/request/lib'`

error was in next.js, 
Any solutions? I have it working without next.js/ gatsby. Any reason why this is not working.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
