### ISSUE TITLE
Cancel a recurring payment (subscription)

### ISSUE THREAD

**Issue by tracend** [coinbase/coinbase-node#15]
There doesn't seem to be a way to programmatically end a subscription through the API.

This is mostly useful for merchants if they want to manage their subscriptions on their end. 

Please point me in the right direction if this functionality is somewhere available.

**Comment by jorilallo** [comment]
We're currently missing this endpoint (as well as ending recurring payments). I'm happy to add these and will reply back to this when they are live and documented.
