### ISSUE TITLE
Upgrade to API v2

### ISSUE THREAD

**Issue by Apercu** [coinbase/coinbase-node#24]
Hi,

Do you plan to switch to the v2 API? The coinbase developers docs recommend to switch to it.  Is there an issue to keep using the library in v1?

Thanks! :)

**Comment by jorilallo** [comment]
@Apercu Updating this library to v2 is on our list. While the API is pretty different, the library will follow the same patterns and API so we try to make it easy for developers to bump from v1 to v2 once the new version is released

**Comment by Apercu** [comment]
Okay nice to ear. I've started my own little version of the library. Would be glad to help if you need

**Comment by GustavoRPS** [comment]
+1

**Comment by maksim-s** [comment]
We just pushed an update to support API v2. Let us know what you think! https://developers.coinbase.com/blog/2015/10/19/node-library-update

**Comment by GustavoRPS** [comment]
Thx @maksim-s!

**Comment by GustavoRPS** [comment]
Can add tag 2.0.0? :wink:

**Comment by chadwhitaker** [comment]
@maksim-s As @GustavoRPS mentioned, can you tag 2.0.0 please? :)
