### ISSUE TITLE
Put full docs online

### ISSUE THREAD

**Issue by lorensr** [coinbase/coinbase-node#3]
```
You can generate html documentation by running the command:

npm install && npm run docs

Open generated html files in docs/ dir with a browser.
```

It would be nice if there was a public website with this, linked to in the README

**Comment by jorilallo** [comment]
@lorensr This would be nice but it doesn't seem that `docco` has support for generating `index.html`. There might be some other module that helps. I'll leave this open until I have time to research this but if you have time, take a stab at it and I'm happy to push them out as GitHub Pages.

**Comment by lorensr** [comment]
I see. This might work:

https://github.com/mbrevoort/docco-husky

And here's an open FR:

https://github.com/DavidSouther/grunt-docco/issues/31

**Comment by jorilallo** [comment]
Thanks, I'll have to take a look little later as I want to be sure that we don't blow up requirements (`docco` is really small as is).
