### ISSUE TITLE
GetAccounts always returns 403

### ISSUE THREAD

**Issue by dragonbanshee** [coinbase/coinbase-node#30]
I am trying to use client.getAccounts with OAuth accessToken and refreshToken, using wallet:accounts:read, but I am always getting a 403 error.

I tried to add the scopes `wallet:accounts:create`, `wallet:accounts:delete`, and `wallet:accounts:update`, but none of them allow me to retrieve the accounts.

```javascript
var client = new Coinbase.Client({
    //_db is a json object containing the accessToken and the refreshToken

    "accessToken": _db.accessToken, 
    "refreshToken": _db.refreshToken,
    'baseApiUri': 'https://api.sandbox.coinbase.com/v1/',
    'tokenUri': 'https://api.sandbox.coinbase.com/oauth/token'
});
```

**Comment by aianus** [comment]
What's the exact error you're getting? There are a few different ones that would result in a 403: https://github.com/coinbase/coinbase-node#error-handling.

**Comment by jorilallo** [comment]
@dragonbanshee `wallet:accounts:read` should be enough. Can you inspect the response payload for more information?

**Comment by jorilallo** [comment]
@dragonbanshee Sorry, the node lib is currently targeted for v1 API and its scopes are different from v2. In this case you need `user` scope. Sorry about that, we're going to update this library soon

**Comment by jorilallo** [comment]
To get notified, I would suggest that you follow issue #24
