### ISSUE TITLE
Update readme: callback verification permissions

### ISSUE THREAD

**Issue by lorensr** [coinbase/coinbase-node#31]
`verifyCallback` is called on the `client`, and you can't create a `client` without an API keypair. Is a keypair actually necessary for callback verification? If yes, what are the minimum permissions needed on that keypair? Thanks!

```
Verifying merchant callback authenticity

if (client.verifyCallback(req.raw_body, req.headers['X-Signature'])) {
  // Process callback
}
```

**Comment by aianus** [comment]
The keypair is not actually used in verifying callbacks, feel free to use any keypair in the creation of the client if this is the only method you're going to use.
