### ISSUE TITLE
AccountBase errors on getTransaction for USDWallet Account

### ISSUE THREAD

**Issue by nicovalencia** [coinbase/coinbase-node#33]
When I query `getTransactions` for my USD Wallet Account id, [this line](https://github.com/coinbase/coinbase-node/blob/master/lib/model/AccountBase.js#L61) throws an error since the result data returned is an empty array (see below):

Result from API:
```
{ pagination:
   { ending_before: null,
     starting_after: null,
     limit: 25,
     order: 'desc',
     previous_uri: null,
     next_uri: null },
  data: [],
  warnings:
   [ { id: 'invalid_version',
       message: 'Please supply a valid API version in YYYY-MM-DD format',
       url: 'https://developers.coinbase.com/api#versioning' } ] }
```

Is AccountBase expecting `data[0]` to always have an object returned from the API? If not, can we add something like this to AccountBase:

```
  this.client._getHttp(path, args, function onGet(err, result) {
    if (!handleError(err, result, callback)) {

      // Handle empty data response from API:
      if (!result.data.length) {
        return callback(null, result.data)
      }

      var ObjFunc = self.client._stringToClass(result.data[0].resource);
      var objs = _.map(result.data, function onMap(obj) {
        return new ObjFunc(self.client, obj, self);
      });
      callback(null, objs, result.pagination);
    }
  }, headers);
```

I'm happy to submit a PR -- just getting my feet wet with the library, so I wanted to check in on intent first before submitting anything.

Thanks!

:pineapple:

**Comment by nicovalencia** [comment]
Just noticed this only happens when there have been *no* transactions on an account, since the response just returns an empty array.

**Comment by jorilallo** [comment]
@nicovalencia thanks for the report. We're little backlogged right now so fixing this might take over the thanksgiving. If you want to submit a PR, we're happy to take a look.

**Comment by nicovalencia** [comment]
All good, man -- no rush. I would love to take a stab at a PR, but I've been slammed w/ work lately. Thanks for putting these adapters together, it really makes integrations and app building easy.

:apple:

**Comment by maksim-s** [comment]
Fixed here https://github.com/coinbase/coinbase-node/commit/288d1b708b6f175d10c00625835a2339d2d8e2fe
