### ISSUE TITLE
ReferenceError: Transaction is not defined

### ISSUE THREAD

**Issue by jborseth** [coinbase/coinbase-node#35]
Attempting to call getTransactions results in `ReferenceError: Transaction is not defined` on line #33 
node_modules/coinbase/lib/model/Address.js:33

https://github.com/coinbase/coinbase-node/blob/master/lib/model/Address.js#L33

The `Transaction` variable is not defined in that file.

**Comment by maksim-s** [comment]
Fixed here https://github.com/coinbase/coinbase-node/commit/288d1b708b6f175d10c00625835a2339d2d8e2fe
