### ISSUE TITLE
Address.getTransactions is bugged

### ISSUE THREAD

**Issue by manuel-di-iorio** [coinbase/coinbase-node#37]
This is how I tried:

    var Address = require('coinbase').model.Address,

    client.getAccount("myAccountID", function(err, account) {
        if (err) return console.log(err);
				
        var address = new Address(client, {id: "myAddress"}, account);

        address.getTransactions(null, function(err, transactions) {
            if (err) return console.log(err);
					
	        console.log(transactions);
	    });
    });

The error I got:

    myAppPath\node_modules\coinbase\lib\model\Address.js:33
        'ObjFunc'  : Transaction,
                 ^

    ReferenceError: Transaction is not defined
        at Base.Address.getTransactions (myAppPath\node_modules\coinbase\lib\model\Address.js:33:18)
    etc..

---

Due that the method seems to be bugged, I tried to prototyping a new similar method with:

    var Address = require('coinbase').model.Address,
        Transaction = require('coinbase').model.Transaction,
        _           = require('lodash');

    Address.prototype.getAllTransactions = function(args, callback) {
        var opts = {
            'colName'  : 'addresses/' + this.id + '/transactions',
            'ObjFunc'  : Transaction,
        };

        this.account._getAll(_.assign(args || {}, opts), callback)
    };

This time, the error got is:

    myAppPath\node_modules\coinbase\lib\model\AccountBase.js:61
      var ObjFunc = self.client._stringToClass(result.data[0].resource);
                                                             ^

    TypeError: Cannot read property 'resource' of undefined
        at onGet (myAppPath\node_modules\coinbase\lib\model\AccountBase.js:61:62)
        at Request.onGet [as _callback] (myAppPath\node_modules\coinbase\lib\ClientBase.js:158:9)

**Comment by jborseth** [comment]
@jorilallo I think this is symptomatic of a bigger issue which is that line 61 of AccountBase.js assumes that `data` will have a length. However, if no data is returned, data is undefined and this error is thrown.

I saw this same error today using getBuys when no buys existed on a given account.

**Comment by manuel-di-iorio** [comment]
@jborseth Yep, in fact logging the result within AccountBase.js

	{ pagination:
	   { ending_before: null,
		 starting_after: null,
		 limit: 25,
		 order: 'desc',
		 previous_uri: null,
		 next_uri: null },
	  data: [],
	  warnings:
	   [ { id: 'invalid_version',
		   message: 'Please supply a valid API version in YYYY-MM-DD format',
		   url: 'https://developers.coinbase.com/api#versioning' } ] }

For the warning: should the API version be supplied from the coinbase lib itself?

**Comment by jborseth** [comment]
The version is optional. If it is not specified, the newest version of the API is used. Or you can specify a YYYY-MM-DD date string when instantiating the client in the same object where you provide your API key and API secret (https://github.com/coinbase/coinbase-node/blob/a7cc79450dd0b55eb0fe4b03ea8ba3a139635a28/lib/ClientBase.js#L54) This locks in the version of the API to the version that was deployed on that date, which is useful for ensuring that the version of the API that you developed against is used. 

Try specifying a date (e.g. today's date) to see if that resolves this different error. If that doesn't resolve it, this would make a good separate github issue.

**Comment by manuel-di-iorio** [comment]
Nope @jborseth, even with the locked version, the issue is the same. It's a underlying bug

**Comment by maksim-s** [comment]
fixed here https://github.com/coinbase/coinbase-node/commit/288d1b708b6f175d10c00625835a2339d2d8e2fe
