### ISSUE TITLE
Add sandbox support

### ISSUE THREAD

**Issue by manuel-di-iorio** [coinbase/coinbase-node#38]
If I set the API keys of mine sandbox account, coinbase gives the error "AuthenticationError".
Instead, with the API keys of the standard account, it works.

Am I wrong or the sandbox isn't supported yet?

**Comment by manuel-di-iorio** [comment]
I saw the documentation.. I was in wrong :)

**Comment by vasuchawla** [comment]
@manuel-di-iorio  can I please get to know what was wrong, i am facing the same issue :)

**Comment by manuel-di-iorio** [comment]
Hello @vasuchawla, seems like they removed the sandbox configuration from the readme file (https://github.com/coinbase/coinbase-node/commit/1aaad7be82237c4b84251148cfa8029c023fd4cf)

This was the old code:

```javascript		
var Client = require('coinbase').Client;		
var client = new Client({		
    <api keys or access tokens here>		
    'baseApiUri': 'https://api.sandbox.coinbase.com/v2/',		
    'tokenUri': 'https://api.sandbox.coinbase.com/oauth/token'		
});		
```

I don't know why, maybe this is no longer supported? Try the code above or open a new github issue :)
