### ISSUE TITLE
The new v.2.0.1 has a little bug

### ISSUE THREAD

**Issue by manuel-di-iorio** [coinbase/coinbase-node#46]
myAppPath\node_modules\coinbase\lib\model\Notification.js:
	14
	function Notification(client, data) {
	^^^^^^^^

	SyntaxError: Unexpected token function

It will be thrown just with:

	var Client = require('coinbase').Client,

	client = new Client({
		'apiKey': "apiKey", 
		'apiSecret': "apiSecret"
	});

Pull request: https://github.com/coinbase/coinbase-node/pull/47

**Comment by essofluffy** [comment]
I had this bug as well. Your pull request contains the correct fix.

**Comment by maksim-s** [comment]
thank you for fixing!
