### ISSUE TITLE
How to send bitcoins from multiple accounts to multiple addresses in one call ?

### ISSUE THREAD

**Issue by manuel-di-iorio** [coinbase/coinbase-node#48]
This feature seems to not to be implemented in the APIs.
Is there a plan date to when to add it? Maybe V3 ?

This may help to reduce TX fees for sendings from multiple accounts to multiple bitcoin addresses

Example call:

	client.getAccounts('account1,account2', function(err, accounts) {
	    accounts.sendMoney({'to': 'address1,address2,address3',
                'amounts': '0.1,0.05,1.8',
                'currency': 'BTC'}, function(err, tx) {
                    console.log(tx);
                });
        });
	});

**Comment by jorilallo** [comment]
@manuel-di-iorio at the moment we don't have plans to allow sending to multiple addresses. It's something we might consider for future additions but for now you need to separate each transaction
