### ISSUE TITLE
verifyCallback with Express

### ISSUE THREAD

**Issue by aristidesfl** [coinbase/coinbase-node#50]
Hi, I'm trying to use the verifyCallback with Express.

The problem seems to be that I'm using bodyParser.json() app wide which populates `req.body`, but it doesn't make the raw_body available. Any way around this, like `JSON.strigify(req.body)`? Other ideas?

Thanks!

**Comment by jorilallo** [comment]
@aristidesfl I don't have extensive experience with Express but something like this might work:

http://stackoverflow.com/a/13565786/268565

**Comment by aristidesfl** [comment]
@jorilallo thanks for the link

For future reference, this is the best method I've found so far: https://github.com/expressjs/body-parser/issues/83#issuecomment-80784100

**Comment by jorilallo** [comment]
@aristidesfl :+1:
