### ISSUE TITLE
No cb-version?

### ISSUE THREAD

**Issue by aristidesfl** [coinbase/coinbase-node#53]
Hi, noticed a few odd things: 

1. The notification header `X-Signature` described in the README does not exist, but instead a `cb-signature` header contains the signature.

2. The notification header `cb-version` says `BETA`

3. [No default API verison seems to be set](https://github.com/coinbase/coinbase-node/blob/4cd58e1659bd0fe793d45554f7a0cf8e30a3673e/lib/ClientBase.js#L136) unless it is provided by the user, yet nothing in the README suggests  this. I would expect the version to automatically be set to the date that the version of `coinbase-node` I'm using was released, or to a version which is known to work with that library version.

4. Tried to set the version of the API to `2016-01-04` (the date version 2.0.2 was released), but the callback notification is still sent back with the same headers described in 1) and 2)

Am I doing something wrong?

**Comment by maksim-s** [comment]
Hey,

Thanks for reporting the issues. Everything should be fixed now in 2.0.3. You can set the notifications version on the API settings page here https://www.coinbase.com/settings/api

**Comment by aristidesfl** [comment]
Shouldn't the version be set by the library in order for it to always be compatible with the version being used?
