### ISSUE TITLE
Promisification trouble: TypeError: Cannot read property '_getOneHttp' of undefined

### ISSUE THREAD

**Issue by dsernst** [coinbase/coinbase-node#59]
When I try to promisify this library with [`bluebird`](https://github.com/petkaantonov/bluebird), I get the following error:

```
Unhandled rejection TypeError: Cannot read property '_getOneHttp' of undefined
```

This happens from `bluebird`'s [`promisifyAll`](http://bluebirdjs.com/docs/api/promise.promisifyall.html), and from [manual promisification](http://bluebirdjs.com/docs/api/promise.promisify.html):

```
Unhandled rejection TypeError: Cannot read property '_getOneHttp' of undefined
    at Client.getAccount (/Users/dsernst/Documents/coinbase-fu/node_modules/coinbase/lib/Client.js:65:7)
    at tryCatcher (/Users/dsernst/Documents/coinbase-fu/node_modules/bluebird/js/release/util.js:11:23)
    at ret (eval at <anonymous> (/Users/dsernst/Documents/coinbase-fu/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at useCoinbase (/Users/dsernst/Documents/coinbase-fu/send-payments.js:123:45)
```

Here's the invoked line 123, the final line listed in the above stack trace, that leads to this problem:

``` js
return Promise.promisify(coinbase.getAccount)(coinbaseAccountId)
  .then(account => {
```

---

I've found I was able to fix this by changing it to:

``` js
return Promise.fromCallback(function(cb) {
  coinbase.getAccount(coinbaseAccountId, cb)
})
.then(account => {
```

The issue is resolved if I use this manual [`Promise.fromCallback` method](http://bluebirdjs.com/docs/api/promise.fromcallback.html) every time, but it would still be nice if this library could be improved to not require this, and we could just use [`.promisifyAll`](http://bluebirdjs.com/docs/api/promise.promisifyall.html) once when the library is first imported.

I also wanted to post this issue in case anyone else runs into the same problem.

Thanks 😄

**Comment by rajweb** [comment]
var Promise = require('bluebird');
var Client = require('coinbase').Client;
var bitcoin = new Client({
  'apiKey': xxxxxxxxx,
    'apiSecret': xxxxxxx,
    'baseApiUri': xxxxxxxx,
    'tokenUri': xxxxxxxxxxxx
});

return Promise.fromCallback(function(cb) {
    bitcoin.getSpotPrice({'currency': 'INR'}, cb)
  })
  .then(handleEntityNotFound(res))
  .then(responseWithResult(res))
  .catch(handleError(res));

got error message as follow:

TypeError: Promise.fromCallback is not a function

**Comment by Robinlemon** [comment]
Why not use something like this

```
function GetBTC(Callback){
	Wallet.getAccounts({}, function(Error, Accounts) {
		if(Error) return console.log(Error);
		return Callback(Accounts[0].balance.amount);
	});
}
```
Then....
```
GetBTC(function(BTC){
    console.log(`I have ${BTC} BTC`);
});
```

**Comment by givanse** [comment]
The error comes from a context change. This will work:

```
// I prefer to use my own, but the solution will be the same with Bluebird
function promisify(errFirstCallback) {
  const fun = function() {
    const promise = new window.Promise(function(resolve, reject) {
      errFirstCallback(arguments, function(err, result) {
        if (err) {
          reject(err);
        }
        resolve(result);
      });
    });

    return promise;
  };

  return fun;
}

// This is the key
promisify(client.getAccounts.bind(client));
```

**Comment by dsernst** [comment]
@rajweb: `Promise.fromCallback` is from the [`bluebird` library](https://github.com/petkaantonov/bluebird). Sorry for the confusion.

@Robinlemon: Your solution works, sure, with the drawback of not Promisify-ing the methods 😄. I'm not working anymore on the project that needed this, and tbh I don't fully remember the context. But, if I had to guess, the coinbase API was being used in a big chain of Promises, so using a callback to handle asynchrony in the middle of it would break consistency and make the code less understandable. Nonetheless, your code looks like it would work. And just fyi, [`bluebird.fromCallback`](http://bluebirdjs.com/docs/api/promise.fromcallback.html) is shorthand for what you're proposing, and returns a Promise.

@givanse: Thanks for the `.bind` tip. 😄

**Comment by tleunen** [comment]
Until there's a real support for promises, you can do this:
```js
const { promisify } = require('util');

const getAccountsAsync = promisify(client.getAccounts).bind(client);
```

**Comment by leonidez** [comment]
You can also promisify the whole client by doing the following before calling `new`:

```
const { promisify } = require('util')
const { Client } = require('coinbase')

Object.keys(Client.prototype).forEach(method => {
  Client.prototype[method] = promisify(Client.prototype[method])
})
```

**Comment by Robinlemon** [comment]
You can also do this manually

```
const Promise = require('bluebird');

function GetBTC(){
    return new Promise((Resolve, Reject) => {
        return Wallet.getAccounts({}, function(Err, Accounts) {
            if(Err) return Reject(Err);
            return Resolve(Accounts[0].balance.amount);
        });
    });
}

GetBTC().then(BTC => console.log(`I own ${BTC} BTC`)).catch(console.error);
```

**Comment by dsernst** [comment]
I'm going to close this issue for now.

If you want it re-opened feel free to say something, but I feel weird being responsible for this open issue since I'm no longer working on the project that needed this.

Cheers
