### ISSUE TITLE
Separate api access code base from oauth code base completely

### ISSUE THREAD

**Issue by Levino** [coinbase/coinbase-node#6]
Just a suggestion: Why don't you create two packages in npm for coinbase? One that does solely oauth requests and the other one with apikey / secret.

Currently it is really confusing when trying to set it up with using oauth because for example one has to set the param "apiKey" to what is actually the "Client ID" (at least I guess so).

Please elaborate a little on how the design is envisioned to be. I think there might be even security reasons not to mix the functionality.

**Comment by jorilallo** [comment]
I don't really see the OAuth2 flow being part of the job of the client library as it's usually really environment specific, mainly connected to your web framework. Right now we accept your tokens and take care of refreshing them but you need to build the authentication flow yourself. If you're using Passport for auth, I recommend that you take a look at [passport-coinbase](https://www.npmjs.com/package/passport-coinbase) strategy. At the moment we don't have plans for a separate generic library but can build plugins for new popular auth frameworks if needed.
