### ISSUE TITLE
getAddresses internal error

### ISSUE THREAD

**Issue by unutoiul** [coinbase/coinbase-node#68]
client.getAccount(id, function(err, account) {
			  account.getAddresses(function(err, addresses) {
			    console.log(addresses);
 });
});
I'm trying to get all of my addresses for a wallet , the account is return correct but after that I get this error:
internal implementation error..

if i will use 

account.getAddresses(null, function(err, addresses) {
			    console.log(addresses);
 });
 just found out is working but I can't convert the addresses object using JSON.parse() method.

**Comment by Kasp42** [comment]
```
account.getAddresses(null, function(err, addresses) {
addresses.forEach(function(item){console.log(item.address)})
});
```

**Comment by unutoiul** [comment]
Thank you that is working fine, but 

client.getAccounts({}, function(err, accounts) {
	console.log(err);
});

give me all of the accounts but doesn't have the forEach function and I can't do JSON.parse(), why is not consistent on responses?

Thanks,
Lucas

**Comment by sh6khan** [comment]
Hey Lucas

the `accounts` should be an array object, not a JSON. Which is why you cant to `JSON.parse()`. However you should be able to do `forEach`

```
client.getAccounts({}, function(err, accounts) {
  accounts.forEach(function(account){
    console.log(account);
  })
});
```

this should give you a list of all the accounts that are accessible through your API. Ive tested this locally myself and there weren't any issues

**Comment by unutoiul** [comment]
Hi,

It is an object only when i returning more then 1 results...if returning only 1 results you can't do forEach loop...

Is there a bug or supposed pust to work like that?

Thanks

**Comment by mike-eason** [comment]
Hi @unutoiul,

Can you provide your code? I'm using this and it's absolutely fine:

```
require('dotenv').config();

const coinbaseClient = require('coinbase').Client;
const coinbase = new coinbaseClient({'apiKey': process.env.API_KEY, 'apiSecret': process.env.API_SECRET});

coinbase.getAccounts({}, function(err, accounts) {
    if (err)
        return console.error(error);

    accounts.forEach(function(account) {
        console.log(`${account.name}: ${account.balance.amount} ${account.balance.currency} / ${account.native_balance.amount} ${account.native_balance.currency}`);
    });
});
```

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
