### ISSUE TITLE
Do not require apikey and apisecret when using oauth in Client constructor

### ISSUE THREAD

**Issue by Levino** [coinbase/coinbase-node#7]
I use oauth for requests to the API via the Client object.

If i create a Client object like: 

```
var Client = require('coinbase').Client;
var client = new Client({
                          'apiKey'       : " ",
                          'apiSecret'    : " ",
                          'accessToken'  : accessToken,
                          'refreshToken' : refreshToken
                        });
```

All calls work fine, meaning that the apiKey and apiSecret is ignored.

When I do:

```
var Client = require('coinbase').Client;
var client = new Client({
                          'accessToken'  : accessToken,
                          'refreshToken' : refreshToken
                        });
```

The "no apiKey" Error is thrown. To be honest the Error is not very helpful. I would appreciate a "CoinbaseError" Object to be thrown here. But anyhow. If an accessToken is set, why bother requiring a key 'apiKey' to be set? That does not really make sense to me.

**Comment by Levino** [comment]
Something else that I am thinking and that somewhat concerns me but I think it is more general: Why do you not require me to sign all queries from my server for a client to be signed by my application secret? If an access token gets leaked one can do whatever one wants with it. I mean where to think these tokens are to be stored for the users when not in a database? The Application Secret can easily be stored at another place. So requiring not only the access token in the request, but also the signature with the Application Secret to be valid would add an additional level of security for pretty low cost...

**Comment by SyRenity** [comment]
@Levino Good catch about empty apiKey and apiSecret!
Took me quite a while to figure them out as cause to the issues we had.

**Comment by jorilallo** [comment]
@Levino Main reason why we're not doing this right now is because it's not a common pattern with Oauth and would most likely cause issues with some implementation. Also, while it's possible to keep the secret more separate, in many cases it's public knowledge (i.e. mobile apps) and provides very little protection. To protect funds better we rely on 2FA on send money action.

**Comment by jorilallo** [comment]
@SyRenity Can you update to newest version of the library? This issue should be fixed there
