### ISSUE TITLE
ES6 Example

### ISSUE THREAD

**Issue by redcap3000** [coinbase/coinbase-node#70]
I was trying to get this to work with ES6 - Heres how:
Might be helpful for others if in the readme.

```
import { Client as client} from 'coinbase';

var coinbase = new client({
    <connection stuff here>
});
```

**Comment by premiumwd** [comment]
@redcap3000  I got client is not constructor, can you help?

**Comment by redcap3000** [comment]
Sorry typo in my example... here it is:
```
 var client =  new coinbase({
      apiKey : q.apiKey,
      apiSecret : q.apiSecret
    });
```

**Comment by premiumwd** [comment]
@redcap3000 I think your a moron who doesn't know what the fuck he is doing. Good day idiot.
