### ISSUE TITLE
client.getTransactions is not a function

### ISSUE THREAD

**Issue by redcap3000** [coinbase/coinbase-node#71]
Trying out the package in ES6 /react environment.
I've gotten getAccounts,sell,send,getBuyPrice working similar to this example, but getTransactions throws an error.... is this a namespace thing? Its a bit confusing, and worse in ES6.
```
import { Client as coinbase} from 'coinbase';

var coinbaseGetTransactions = (coinbaseAccount)=>{
  var client = new coinbase(coinbaseKeys[coinbaseAccount]);
  console.log(client);
  client.getTransactions({},Meteor.bindEnvironment((err,txns)=>{
    txns.forEach((txn)=>{
      console.log('my txn status : ' + txn.status);
    }); 
  }))
}
```

```
TypeError: client.getTransactions is not a function
    at _coinbaseGetTransactions (server/coinbaseServer.js:121:10)
    at [object Object].coinbaseGetTransactions (server/coinbaseServer.js:142:12)
```

Also using meteor but I doubt its causing the issue.

**Comment by premiumwd** [comment]
Hey @redcap3000 were you able to get this working with angular? Can you help me?

**Comment by redcap3000** [comment]
Nope. Maybe coinbase can help? Are they alive? Hellloooooo coinbase. Anyooonneee therreeee? Obviously not.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
