### ISSUE TITLE
Prepare "getAccounts" for pagination

### ISSUE THREAD

**Issue by Levino** [coinbase/coinbase-node#8]
https://github.com/coinbase/coinbase-node/blob/master/lib/Client.js#L106
https://github.com/coinbase/coinbase-node/blob/master/lib/model/Account.js#L165

Compare these two guys. Account.getAddresses is prepared for pagination. To get pagination working for Client.getAccounts one has to rewrite the whole function. Not really following a pattern here. I would also pass the same parameters to the Client.getAccounts function.

**Comment by jorilallo** [comment]
Closing as this issue is affecting older version of the library
