### ISSUE TITLE
TypeError: Cannot read property 'forEach' of null

### ISSUE THREAD

**Issue by donfrigo** [coinbase/coinbase-node#80]
Hello all,

I am quite new to node.js, but still haven't been able to connect to my wallet. I have created my api keys and copied them to the code, but I get the following error: 

> accounts.forEach(function(acct) {
TypeError: Cannot read property 'forEach' of null

My code is copied from the website: 

```
var Client = require('coinbase').Client;

var client = new Client({
  'apiKey': 'IPutMyKeyHere',
  'apiSecret': 'PutMySecretHere'});

client.getAccounts({}, function(err, accounts) {
  accounts.forEach(function(acct) {
    console.log('my bal: ' + acct.balance.amount + ' for ' + acct.name);
  });
});
```

Looking forward to your answer!
Thanks!

**Comment by ejuopperi** [comment]
For security reasons a newly created api-key is disabled the first 48h after creation, when did you create the api-key?

**Comment by DanielWilson1** [comment]
Hey ejuopperi I'm having the exact same issue and my api-key was created about 4 days ago. Other than installing coinbase, are there any files I need to copy over to get this to work? I'm pretty new to node.js as well but I thought this was something I could handle.

**Comment by sh6khan** [comment]
If your `accounts` variable is null, the coinbase api likely returned an error.
It would be helpful to print out your error

```
client.getAccounts({}, function(err, accounts) {
  if (err != null) {
    console.log(err);
  }
  
  // accounts.forEach(function(acct) {
  //   console.log('my bal: ' + acct.balance.amount + ' for ' + acct.name);
  // });
});
```

**Comment by yofi2tofi** [comment]
i have same problem. But i took my api key a day ago

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
