### ISSUE TITLE
no callback - check method signature

### ISSUE THREAD

**Issue by khwerhahn** [coinbase/coinbase-node#86]
Hi, 

I always get the error `no callback - check method signature` thrown. What am I doing wrong?
```
client.getAccount('xyz', function(err, account) {
  account.getTransactions(function(err, trxs) {
   console.log(trxs);
  });
});
```

**Comment by gdcrocx** [comment]
Could you try this.
`client.getAccount(**{ 'account_id':**'xyz'**}**, function(err, account) {
  account.getTransactions(function(err, trxs) {
   console.log(trxs);
  });
});`

**Comment by milesalex** [comment]
Getting this error too :(

```
../coinbase/lib/errorHandler.js:60                                            
  if (!callback) {throw "no callback - check method signature";}                                                       
                  ^                                                                                                    
no callback - check method signature
```

**Comment by milesalex** [comment]
@khwerhahn You figure it out?

**Comment by yunyeng** [comment]
Try 
account.getTransactions(null, function(err, trxs) {
   console.log(trxs);
 });

It expects two parameters, but first one was not defined in docs, hope they fix it.

**Comment by athJ** [comment]
Yes , getTransactions accepts two args ,yunyeng solution worked for me

**Comment by luanpv** [comment]
Try

var Client = require('coinbase').Client;
var client = new Client({'apiKey': 'apiKey',
                         'apiSecret': 'apiKey'});
client.getAccount('primary', function(err, account) {
  account.createAddress(null, function(err, address) {
    console.log(address);
  });
});

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
