### ISSUE TITLE
Promise API? 

### ISSUE THREAD

**Issue by johnbrett** [coinbase/coinbase-node#89]
Hey great work on this!

Would it be possible to expose a promise API from this library? There is huge increase in people using the new `async/await` syntax for building apps, which requires an API to expose promises. 

Can help out with this if it's wanted!

**Comment by nearwood** [comment]
I've got a start to this. All of the Client methods and a few Account ones:
https://github.com/nearwood/coinbase-node

**Comment by psperber** [comment]
I created this variant: https://github.com/coinbase/coinbase-node/pull/94

**Comment by tleunen** [comment]
Until there's a support for promises, you can use `util.promisify` to have the same behavior.

```
const { promisify } = require('util');

const getAccountsAsync = promisify(client.getAccounts).bind(client);
```

**Comment by psperber** [comment]
good call! Thank you for that hint.

**Comment by jkuchar** [comment]
How are you dealing with pagination? Promisify returns just the first parameter from original callback.

**Comment by damianobarbati** [comment]
Please guys, it's 2019. 

The callback API is pretty outdated by now, if you didn't come out with native promise API least adhere to the convention of "return a promise if no callback was provided" 🙏🏻

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
