### ISSUE TITLE
UnauthorizedError: invalid signature

### ISSUE THREAD

**Issue by MythlinMasterdo** [coinbase/coinbase-node#96]
While attempting to create a new wallet with the Coinbase-node API I am constantly getting errors back from the client.getAccounts() call. 

```
var Client = require('coinbase').Client;

var client = new Client({
  'apiKey': 'privateKeyHere',
  'apiSecret': 'privateKeyHere'
});

client.getAccounts({}, function(err, accounts) {
  console.log(err);
  accounts.forEach(function(acct) {
    console.log('my bal: ' + acct.balance.amount + ' for ' + acct.name);
  });
});
```

I console logged my client and I am successfully connecting to Coinbase. Can anyone see what I am doing wrong?

**Comment by lumio** [comment]
Same error here. Could it be, that the README is outdated?

**Comment by MillHaus33** [comment]
Same error for me

**Comment by scredii** [comment]
Same in 2018.... Coinbase are u here ?

**Comment by Olivierlu1** [comment]
Same as of June 2018.... Has anyone fixed this?

**Comment by mayoralito** [comment]
Well... I can tell sadly that I get this in 2019...
`error:  AuthenticationError: invalid signature` even when the error is clear enough the `apiKey/apiSecret` are correct according to the **API Access** dashboard.

**Comment by mayoralito** [comment]
So it turns out that they are deprecating (apparently) usage of apiKey/apiSecret. I tested using 
```
var Client = require('coinbase').Client;
client = new Client({
                    'accessToken': '', 
                    'refreshToken': ''
                });

client.getAccounts({}, function(err, accounts) {
  console.log(err);
  accounts.forEach(function(acct) {
    console.log('my bal: ' + acct.balance.amount + ' for ' + acct.name);
  });
});
```

And this time it worked!

**Comment by wodinga** [comment]
Omg was this mentioned anywhere? I was following the docs and nothing was working for me.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
